### ISSUE TITLE
Feature - Hide the stats.json from project summary

### ISSUE THREAD

**Issue by Mozart409** [relative-ci/roadmap#18]
Hello,

awesome product by the way. Been using it for three days and I love it.
I want to hide my stats.json from the project summary. Is that possible?

<img width="1075" alt="grafik" src="https://user-images.githubusercontent.com/38767929/89519174-3af2f780-d7dc-11ea-9f4f-fe1f0594c4fa.png">
<img width="1075" alt="grafik" src="https://user-images.githubusercontent.com/38767929/89519189-421a0580-d7dc-11ea-9e56-0ede7ec2298e.png">

Maybe we can hide the stats.json file from the relative.config.js?

**Comment by vio** [comment]
To ignore assets from the report, you need to pass [webpack `stats.excludeAssets`](https://webpack.js.org/configuration/stats/#statsexcludeassets) option to [`RelativeCiAgentWebpackPlugin` or `StatsWritterPlugin`](https://relative-ci.com/documentation/faq#agent--exclude-assets-modules):

### Webpack plugin example
```javascript
// webpack.config.js
const { RelativeCiAgentWebpackPlugin } = require('@relative-ci/agent');

module.exports = {
  // ... your webpack config
  plugins: [
    // ... other plugins
    new RelativeCiAgentWebpackPlugin({
      stats: {
        excludeAssets: [/webpack-stats.json/]
      }
    })
  ]
};
```

### CLI setup example
```javascript
// webpack.config.js
const { StatsWriterPlugin } = require("webpack-stats-plugin")

module.exports = {
  // ... your webpack config
  plugins: [
    // ... other plugins

    // Write out stats file to build directory.
    new StatsWriterPlugin({
      filename: 'stats.json',
      stats: {
        context: './src', // optional, will improve readability of the paths
        assets: true,
        entrypoints: true,
        chunks: true,
        modules: true,
        excludeAssets: [/webpack-stats.json/]
      }
    })
  ]
}
```
