### ISSUE TITLE
[RelativeCI] Allow drill down info for assets and other visualizations

### ISSUE THREAD

**Issue by jflayhart** [relative-ci/roadmap#20]
It would be really nice to drilldown into WHAT (and even where) the offending asset(s) are with things like file size and file name, etc:

<img width="1320" alt="Screen Shot 2021-01-24 at 3 57 56 PM" src="https://user-images.githubusercontent.com/6808172/105648921-993b9180-5e73-11eb-9eed-b1fbb3d30d60.png">

Then to understand WHY it might be  helpful to get more insight integrating a tool like [webpack-bundle-analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer) into this GUI.

Just want a more wholesome look at what is wrong and "why" to help understand how to fix a large bundle.

**Comment by vio** [comment]
Thanks @jflayhart! I think this issues are related:

1. https://github.com/relative-ci/bundle-stats/issues/594
2. https://github.com/relative-ci/bundle-stats/issues/623
3. https://github.com/relative-ci/bundle-stats/issues/622

**Comment by vio** [comment]
FYI, all the sections navigations are done now(https://github.com/relative-ci/bundle-stats/issues/594):

> Summary metric item - navigate to the corresponding view
 Bundle size -> Totals tab
 Initial JS size -> Assets tab - entries filtered by type JS and asset type initial
 Initial CSS size -> Assets tab - entries filtered by type CSS and asset type initial
 Cache invalidation -> Assets tab - entries filtered by changed flag
 Asset count -> Assets tab - all entries
 Chunk count -> Assets tab - all chunk entries
 Modules -> Modules tab
 Packages -> Packages tab - all packages
 Duplicate packages -> Packages tab - packages filtered by duplicate flag
  Duplicate package -> Packages tab - entries filtered by package name
Totals by type chart -> Assets tab - entries filtered by type -> #1212
  Totals by type table -> Assets tab - entries filtered by type
Assets -> Modules tab - chunk view -> #1210
Packages -> Modules tab - entries filtered by package -> #1211

will consider this done for now, but feel free to open another issue if you are considering a specific case
