### ISSUE TITLE
Document configuration for CRA

### ISSUE THREAD

**Issue by hboylan** [relative-ci/roadmap#23]
It would be helpful to include a "CRA config" of the [Configure agent webpack plugin](https://relative-ci.com/documentation/setup/webpack-plugin) section of documentation. After some digging, I found the [Use with create-react-app](https://github.com/relative-ci/bundle-stats/tree/master/packages/webpack-plugin#use-with-create-react-app) section did the trick. 

This could be adapted to describe `RelativeCiAgentWebpackPlugin` like the following:

### CRA config:

You will need to customize the default webpack config. That can be done by using [react-app-rewired](https://github.com/timarney/react-app-rewired) which is one of create-react-app's custom config solutions. You will also need [customize-cra](https://github.com/arackaf/customize-cra).

```shell
npm install --dev customize-cra react-app-rewired
```
or
```shell
yarn add --dev customize-cra react-app-rewired
```

Add a script in `package.json`:
```json
"scripts": {
  "build:analyze": "react-app-rewired build"
}
```

Create a file `config-overrides.js` at the same level as `package.json`.
```js
const { RelativeCiAgentWebpackPlugin } = require('@relative-ci/agent')
const { override, addWebpackPlugin } = require('customize-cra')

module.exports = override(addWebpackPlugin(new RelativeCiAgentWebpackPlugin()))
```

**Comment by vio** [comment]
Thank you @hboylan, will add it! ;) I believe [CRA is supporting `--stats`](https://github.com/facebook/create-react-app/pull/8790) now and the output can be consumed by the [@relative-ci/agent CLI](https://relative-ci.com/documentation/setup/cli), will add that case as well.

**Comment by vio** [comment]
Added: https://relative-ci.com/documentation/setup/webpack-plugin#create-react-app. Thanks again @hboylan!
