### ISSUE TITLE
Baseline job label - link to the baseline job

### ISSUE THREAD

**Issue by vio** [relative-ci/roadmap#27]

**Comment by jflayhart** [comment]
not sure if this is relevant, but it would be nice to have the line label or tooltip link to the relevant commit to see what caused a good or bad thing in bundle size:

<img width="1236" alt="Screen Shot 2021-04-13 at 5 18 25 PM" src="https://user-images.githubusercontent.com/6808172/114628444-794e8980-9c7c-11eb-9edb-82fa9f9c90c2.png">

**Comment by vio** [comment]
Thank you @jflayhart, that makes sense. The plan was to show a link tot all the jobs in the corresponding period, but the change depends on other new features. Created https://github.com/relative-ci/roadmap/issues/29 to track it.

**Comment by vio** [comment]
The baseline label is now a link to the corresponding report:
![job-baseline-link](https://user-images.githubusercontent.com/13300/115464172-f5247500-a22c-11eb-90ee-a842e3936079.jpg)

Also, the baseline info and the GitHub compare link are available on the header:
![job-baseline-link--header](https://user-images.githubusercontent.com/13300/115464354-3c126a80-a22d-11eb-926b-5ddafe52197e.jpg)

**Comment by jflayhart** [comment]
this is AWESOME! thanks!
