### ISSUE TITLE
Metric chart tooltip - link to job 

### ISSUE THREAD

**Issue by vio** [relative-ci/roadmap#29]

**Comment by jflayhart** [comment]
for visual reference it would be nice to have the line label or tooltip link to the relevant commit to see what caused a good or bad thing in bundle size:

<img width="1236" alt="Screen Shot 2021-04-13 at 5 18 25 PM" src="https://user-images.githubusercontent.com/6808172/114628444-794e8980-9c7c-11eb-9edb-82fa9f9c90c2.png">

**Comment by vio** [comment]
Added link to the period's latest job:

![project-chart-job-link](https://user-images.githubusercontent.com/13300/115464794-e9857e00-a22d-11eb-85ba-e29135665fe4.jpg)
